apiVersion: v1
kind: Pod
metadata:
  name: hubble-log-collector
spec:
  containers:
    - name: collector
      image: cybersecuritybox/hubble-log-collector:latest
      command: ["hubble"]
      args: ["observe", "-o", "json", "--pod", "default/", "-f"]
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1"
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        privileged: false
        capabilities:
          drop:
            - all
      env:
        - name: HUBBLE_SERVER
          value: "hubble-relay.kube-system:80"
        - name: K8S_CLUSTER_NAME
          value: ""
      envFrom:
        - secretRef:
            name: hubble-log-collector